spring:
  application:
    name: blogstream-webpage
server:
  port: 8080
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    instance-id: ${spring.application.name}:${random.value}
management:
  security:
    enabled: false
